apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
  namespace: default
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: frontend
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30001
  selector:
    app.kubernetes.io/name: frontend
