apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notifications.fullname" . }}-config
  labels:
    {{- include "notifications.labels" . | nindent 4 }}
data:
  app-name: {{ .Values.env.APP_NAME | quote }}
  debug: {{ .Values.env.DEBUG | quote }}
  log-level: {{ .Values.env.LOG_LEVEL | quote }}
