apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notifications.fullname" . }}-secrets
  labels:
    {{- include "notifications.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.secrets.databaseUrl | quote }}
  smtp-host: {{ .Values.secrets.smtpHost | quote }}
  smtp-port: {{ .Values.secrets.smtpPort | quote }}
  smtp-user: {{ .Values.secrets.smtpUser | default "" | quote }}
  smtp-password: {{ .Values.secrets.smtpPassword | default "" | quote }}
  smtp-from: {{ .Values.secrets.smtpFrom | quote }}
  pusher-key: {{ .Values.secrets.pusherKey | default "" | quote }}
  pusher-cluster: {{ .Values.secrets.pusherCluster | default "" | quote }}
